### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [prnmxm/s10#1]
Здравствуйте. Благодарю за проделанную работу.
К сожалению текущая реализация содержит ряд недостатков, не позволяющих мне засчитать работу на данной итерации:

**Можно лучше** файлы logo.svg и cover.jpg, расположенные в репозитории не используются на страничке (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить
**Можно лучше**: Добавить .gitignore. 
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.

Регулярные выражения:
Имя
**Нужно исправить** Нет ограничений на ввод значений в поле "Имя". 
Ожидается, что будет установлено минимальное количество символов равное 2, а максимальное - 20. 
Чтобы добавить необходимо использовать атрибуты:
- minlength,
- maxlength

Адрес сайта:
**Нужно исправить** валидацию не проходят следующие корректные адреса:
http://x.com:30 - доменное имя может состоять из 1го или более символов.
http://some.test.yandex.ru - адрес может содержать поддомены

**Нужно исправить** валидацию проходят следующие некорректные адреса:
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http://www.siteКириллицаНеРазрешена

**Можно лучше** валидацию проходят следующие некорректные адреса:
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 

Email:
**Нужно исправить** Валидацию не проходят следующие корректные адреса сайтов:
some@x.com - доменное имя может состоять из одного символа
x@gmail.com - имя ящика может состоять из одного символа

**Нужно исправить** Валидацию проходят следующие некорректные адреса:
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
`мояпочта@site.ru` - имя ящика не может содержать кириллицу
`-------------------@gmail.com`
`Hungry_developer22@яндекс.com` (доменное имя или адрес не могут содержать кирилицу)
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
`m#i#e@gmail.com`  - специальные  символы кроме `_`,`-`,`.` запрещены к использованию в имени пользователя (в домене все кроме `-`)

Номер телефона:
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7(925 900-90-90
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

**Comment by zlocate** [comment]
Добрый вечер. Осталось пару проблем.
**Нужно исправить** Нет ограничений на ввод значений в поле "Имя".
Ожидается, что будет установлено минимальное количество символов равное 2, а максимальное - 20.
Чтобы добавить необходимо использовать атрибуты:

minlength,
maxlength

Нужно исправить валидацию не проходят следующие корректные адреса:
http://x.com:30 - доменное имя может состоять из 1го или более символов.
http://some.test.yandex.ru - адрес может содержать поддомены
https://prnt.sc/s1xorh

**Comment by prnmxm** [comment]
Если вдруг что-то не понравится, то будьте добры скинуть полностью ваши тесты ;)

**Comment by zlocate** [comment]
Приветствую. 
От меня предложение по внедрению базовых тест-кейсов в 10е задание висит в работе, не поверите :) 

(хоть и само задание в текущей формулировке  подразумевает что студент должен сам предусмотреть все кейсы, что, соглашусь перебор. Поэтому я не могу самостоятельно вам скинуть тест-кейсы до вашего запроса :) )

**Comment by prnmxm** [comment]
Если что апдейт уже залит и ждет ревью)

**Comment by zlocate** [comment]
**Нужно исправить** валидацию проходит следующий некорректный адрес сайта:
http://google.ru:/path/to/deep - присутствует : но отсутствует номер порта.
Должно быть либо http://google.ru/path/to/deep либо http://google.ru:90/path/to/deep

Такс, базовые кейсы по адресу сайта ниже:
```
Адрес сайта:
Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
http://ya.ru
https://www.ya.ru
http://google.ru:98/
http://x.com:30
http://google.ru/path/to/deep/
http://my-next-site.ru
http://8.8.8.8:8080
http://8.8.8.8:8080/page/to/deep#
http://some.test.yandex.ru

Негативные кейсы:
Проверку проходит следующий некорректный адреc сайта:
http://www.ya.
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http:something.ru (отсутствуют `//` после протокола) 
zzz://ya.ru (некорректный протокол. Допустимы только http\https)
http:\\google.ru
 httP://google.ru 
http://google.ru:/path/to/deep
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://something (отсутствует доменная зона)
http://1. (некорректный IP, точка на конце)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
http://127. (некорректный IP, точка на конце)
http://127.0..  (некорректный IP, точка на конце)
http://127.0.0.. (некорректный IP, точка на конце) 
http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр) 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
```

**Comment by prnmxm** [comment]
Сейчас как минимум по этим тестам все окей.

**Comment by zlocate** [comment]
Такс, мой недосмотр - в адресе сайта вполне себе могут присутствовать цифры в имени домена в начале.
http://2domains.ru
Поправьте пожалуйста и я засчитаю работу

**Comment by prnmxm** [comment]
Поправил;)

**Comment by zlocate** [comment]
Благодарю за оперативность. 
Работа засчитана! Желаю вам успехов в обучении на данном курсе. 
Надеюсь еще увидимся :)
